<?xml version="1.0"?>
<!DOCTYPE notes [
<!ELEMENT notes (note)+>
<!ELEMENT note (to,from,heading,body,enviado)>
<!ELEMENT to (#PCDATA)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT heading (#PCDATA)>
<!ELEMENT body (#PCDATA)>
<!ELEMENT enviado EMPTY>
]>
<notes>
    <note>
        <to>Tove</to>
        <from>Jani</from>
        <heading>Reminder</heading>
        <body>Don't forget me this weekend</body>
        <enviado/>
    </note>
    <note>
        <to>Ruben</to>
        <from>Ander</from>
        <heading>Reminder</heading>
        <body>Egun on</body>
        <enviado/>
    </note>
</notes>
