<?xml version="1.0"?>
<!DOCTYPE notes [
<!ELEMENT notes (note)+>
<!ELEMENT note (Receptor,Remitente,Asunto,texto,CCO*)>
<!ELEMENT Receptor (#PCDATA)>
<!ELEMENT Remitente (#PCDATA)>
<!ELEMENT Asunto (#PCDATA)>
<!ELEMENT texto (#PCDATA)>
<!ELEMENT CCO EMPTY>
]>
<notes>
    <note>
        <Receptor>fdvjbkz</Receptor>
        <Remitente>Jani</Remitente>
        <Asunto>Reminder</Asunto>
        <texto>Don't forget me this weekend</texto>
        <CCO/>
    </note>
    <note>
        <Receptor>Ruben</Receptor>
        <Remitente>Ander</Remitente>
        <Asunto>Reminder</Asunto>
        <texto>Egun on</texto>
        <CCO/>
    </note>
</notes>